<a href="https://colab.research.google.com/github/ongsoony8382/software-ai-lab/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dates = pd.date_range('20130101', periods=6)

In [4]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

In [6]:
df

                   A         B         C         D
2013-01-01 -1.433651 -0.742755  0.749782  0.010124
2013-01-02  1.565527 -0.773347  2.601487  0.201558
2013-01-03 -1.717392 -0.266935 -1.670954  0.017538
2013-01-04  0.047271  0.304362 -0.617267 -0.463599
2013-01-05  0.831430 -0.557119  0.231937 -0.655327
2013-01-06 -0.689678 -1.060280  0.920621 -0.852593

In [7]:
df.head()

                   A         B         C         D
2013-01-01 -1.433651 -0.742755  0.749782  0.010124
2013-01-02  1.565527 -0.773347  2.601487  0.201558
2013-01-03 -1.717392 -0.266935 -1.670954  0.017538
2013-01-04  0.047271  0.304362 -0.617267 -0.463599
2013-01-05  0.831430 -0.557119  0.231937 -0.655327

In [8]:
df.tail(3)

                   A         B         C         D
2013-01-04  0.047271  0.304362 -0.617267 -0.463599
2013-01-05  0.831430 -0.557119  0.231937 -0.655327
2013-01-06 -0.689678 -1.060280  0.920621 -0.852593

In [9]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.232749 -0.516012  0.369268 -0.290383
std    1.288395  0.479709  1.455074  0.425768
min   -1.717392 -1.060280 -1.670954 -0.852593
25%   -1.247658 -0.765699 -0.404966 -0.607395
50%   -0.321204 -0.649937  0.490860 -0.226738
75%    0.635391 -0.339481  0.877911  0.015685
max    1.565527  0.304362  2.601487  0.201558

In [13]:
df.sort_index(axis = 1, ascending=False)

                   D         C         B         A
2013-01-01  0.010124  0.749782 -0.742755 -1.433651
2013-01-02  0.201558  2.601487 -0.773347  1.565527
2013-01-03  0.017538 -1.670954 -0.266935 -1.717392
2013-01-04 -0.463599 -0.617267  0.304362  0.047271
2013-01-05 -0.655327  0.231937 -0.557119  0.831430
2013-01-06 -0.852593  0.920621 -1.060280 -0.689678

In [14]:
df[0:3]

                   A         B         C         D
2013-01-01 -1.433651 -0.742755  0.749782  0.010124
2013-01-02  1.565527 -0.773347  2.601487  0.201558
2013-01-03 -1.717392 -0.266935 -1.670954  0.017538

In [15]:
df['20130102':'20130104']

                   A         B         C         D
2013-01-02  1.565527 -0.773347  2.601487  0.201558
2013-01-03 -1.717392 -0.266935 -1.670954  0.017538
2013-01-04  0.047271  0.304362 -0.617267 -0.463599

In [16]:
df['20130102':'20130104'], ['A', 'B']

(                   A         B         C         D
 2013-01-02  1.565527 -0.773347  2.601487  0.201558
 2013-01-03 -1.717392 -0.266935 -1.670954  0.017538
 2013-01-04  0.047271  0.304362 -0.617267 -0.463599,
 ['A', 'B'])

In [17]:
df.iloc[[1,2,4], [0, 2]]

                   A         C
2013-01-02  1.565527  2.601487
2013-01-03 -1.717392 -1.670954
2013-01-05  0.831430  0.231937

In [18]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02  1.565527 -0.773347  2.601487  0.201558
2013-01-03 -1.717392 -0.266935 -1.670954  0.017538

In [19]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index = pd.date_range('20130102', periods=6))

In [20]:
df['F'] = s1

In [22]:
df.at[dates[0], 'A'] = 0

In [25]:
df.iat[0,1] = 0

In [26]:
df.loc[:, 'D'] = np.array([5] * len(df))

In [27]:
df

                   A         B         C    D    F
2013-01-01  0.000000  0.000000  0.749782  5.0  NaN
2013-01-02  1.565527 -0.773347  2.601487  5.0  1.0
2013-01-03 -1.717392 -0.266935 -1.670954  5.0  2.0
2013-01-04  0.047271  0.304362 -0.617267  5.0  3.0
2013-01-05  0.831430 -0.557119  0.231937  5.0  4.0
2013-01-06 -0.689678 -1.060280  0.920621  5.0  5.0